# Generated by Django 4.0.6 on 2022-08-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('iban', models.TextField(max_length=100)),
                ('tipo_de_cuenta_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.TextField(max_length=100)),
                ('monto', models.IntegerField()),
                ('tipo_operacion', models.TextField(max_length=200)),
                ('hora', models.DateTimeField()),
            ],
        ),
    ]
