# Generated by Django 4.0.6 on 2022-08-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0002_cuenta_movimientos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
