# Generated by Django 4.0.6 on 2022-08-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0003_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
    ]
