# Generated by Django 4.0.6 on 2022-08-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0004_cuenta_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='account_id',
        ),
    ]
