# Generated by Django 4.0.6 on 2022-08-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0005_remove_cuenta_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='tipo_de_cuenta_id',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='tipo_de_cuenta',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
