# Generated by Django 4.0.6 on 2022-08-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0006_remove_cuenta_tipo_de_cuenta_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='iban',
            field=models.TextField(max_length=24),
        ),
    ]
