# Generated by Django 4.0.6 on 2022-08-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0007_alter_cuenta_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
