# Generated by Django 4.0.6 on 2022-08-26 20:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_prestamos_id_sucursal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='id_sucursal',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='loan_approved_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 8, 26, 20, 58, 3, 182276, tzinfo=utc)),
        ),
    ]
