# Generated by Django 4.0.6 on 2022-08-24 00:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestamos', '0002_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_approved_date', models.DateField(verbose_name=datetime.datetime(2022, 8, 24, 0, 55, 37, 318680, tzinfo=utc))),
                ('loan_month', models.IntegerField(default=1)),
                ('loan_total', models.FloatField(default=0)),
                ('loanType', models.TextField(default='Personales', max_length=40)),
                ('id_cliente', models.IntegerField(default=0)),
            ],
        ),
    ]
