# Generated by Django 4.0.6 on 2022-08-26 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_alter_prestamos_id_sucursal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='loan_approved_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 8, 26, 21, 3, 22, 767181, tzinfo=utc)),
        ),
    ]
