# Generated by Django 4.0.6 on 2022-08-26 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_prestamos_account_id_prestamos_tipo_de_cuenta_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamos',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='prestamos',
            name='id_sucursal',
        ),
        migrations.RemoveField(
            model_name='prestamos',
            name='tipo_de_cuenta_id',
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='loan_approved_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 8, 26, 21, 12, 9, 386207, tzinfo=utc)),
        ),
    ]
