# Generated by Django 4.0.6 on 2022-08-24 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_alter_prestamos_loan_approved_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamos',
            options={'ordering': ('-loan_approved_date',), 'verbose_name': 'Prestamo', 'verbose_name_plural': 'Prestamos'},
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='loan_approved_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 8, 24, 13, 4, 9, 874189, tzinfo=utc)),
        ),
    ]
