# Generated by Django 4.0.6 on 2022-08-26 21:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0007_prestamos_tipo_de_cuenta_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamos',
            name='tipo_de_cuenta_id',
        ),
        migrations.AddField(
            model_name='prestamos',
            name='id_sucursal',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='loan_approved_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 8, 26, 21, 18, 47, 925213, tzinfo=utc)),
        ),
    ]
